Script started on Sun 01 Mar 2020 07:17:09 PM PST
]0;parveza@zuma:~/hw4[parveza@zuma ~/hw4]$ make
gcc -ansi -std=c99 -Wall -c PhotoLab.c -o PhotoLab.o
gcc -ansi -std=c99 -Wall -c FileIO.c -o FileIO.o
gcc -ansi -std=c99 -Wall -c Image.c -o Image.o
gcc -ansi -std=c99 -Wall -c Test_v2.c -o Test.o
gcc -ansi -std=c99 -Wall -c DIPs.c -o DIPs.o
gcc -ansi -std=c99 -Wall -c Advanced.c -o Advanced.o
ar rc libFilter.a Advanced.o DIPs.o
ranlib libFilter.a
gcc -ansi -std=c99 -Wall Image.o Test.o PhotoLab.o FileIO.o -L. -lFilter -o PhotoLab -lm
gcc -ansi -std=c99 -Wall -c -DDEBUG -c PhotoLab.c -o PhotoLab_DEBUG.o
gcc -ansi -std=c99 -Wall -c -DDEBUG FileIO.c -o FileIO_DEBUG.o
gcc -ansi -std=c99 -Wall -c -DDEBUG -c Test_v2.c -o Test_DEBUG.o
gcc -ansi -std=c99 -Wall Image.o Test_DEBUG.o PhotoLab_DEBUG.o FileIO_DEBUG.o -L. -lFilter -o PhotoLabTest -lm
]0;parveza@zuma:~/hw4[parveza@zuma ~/hw4]$ makeexitmake clean[23Gvalgrind --leak-check=full ./PhotoLabTest[23G./PhotoLab[K

-------------------------
1: Load a PPM image
2: Save the image in PPM and JPEG format
3: Change the color image to black and white
4: Sharpen the image
5: Change the hue of image
6: Add Noise to an image
7: Posterize an image
8: Add Motion Blur 
9: Enlarge the picture by percentage 
10: Crop a square potion of the image 
11: Adjust the Brightness and Contrast of an image 
12: Test all functions
13: Exit

-------------------------
Please make your choice: 12
AutoTest finished successfully.

-------------------------
1: Load a PPM image
2: Save the image in PPM and JPEG format
3: Change the color image to black and white
4: Sharpen the image
5: Change the hue of image
6: Add Noise to an image
7: Posterize an image
8: Add Motion Blur 
9: Enlarge the picture by percentage 
10: Crop a square potion of the image 
11: Adjust the Brightness and Contrast of an image 
12: Test all functions
13: Exit

-------------------------
Please make your choice: 13

You exit the program.
]0;parveza@zuma:~/hw4[parveza@zuma ~/hw4]$ ./PhotoLab[23Gmake[Kexitmake clean[23Gvalgrind --leak-check=full ./PhotoLabTest
==19224== Memcheck, a memory error detector
==19224== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==19224== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==19224== Command: ./PhotoLabTest
==19224== 
applestore.ppm was read successfully!
original.ppm was saved successfully. 
original.jpg was stored for viewing. 
LoadImage & SaveImage tested!

applestore.ppm was read successfully!
bw.ppm was saved successfully. 
bw.jpg was stored for viewing. 
Black and White tested!

applestore.ppm was read successfully!
sharpen.ppm was saved successfully. 
sharpen.jpg was stored for viewing. 
Sharpen Detection tested!

applestore.ppm was read successfully!
hue.ppm was saved successfully. 
hue.jpg was stored for viewing. 
Hue tested!

applestore.ppm was read successfully!
noise.ppm was saved successfully. 
noise.jpg was stored for viewing. 
Noise tested!

applestore.ppm was read successfully!
posterize.ppm was saved successfully. 
posterize.jpg was stored for viewing. 
Posterization tested!

applestore.ppm was read successfully!
blur.ppm was saved successfully. 
blur.jpg was stored for viewing. 
MotionBlur tested!

applestore.ppm was read successfully!
enlarge.ppm was saved successfully. 
enlarge.jpg was stored for viewing. 
Enlarge tested!

applestore.ppm was read successfully!
square.ppm was saved successfully. 
square.jpg was stored for viewing. 
Square tested!

applestore.ppm was read successfully!
brightnessandcontrast.ppm was saved successfully. 
brightnessandcontrast.jpg was stored for viewing. 
Brightness and Contrast tested!

AutoTest finished successfully.
==19224== 
==19224== HEAP SUMMARY:
==19224==     in use at exit: 0 bytes in 0 blocks
==19224==   total heap usage: 72 allocs, 72 frees, 10,492,576 bytes allocated
==19224== 
==19224== All heap blocks were freed -- no leaks are possible
==19224== 
==19224== For counts of detected and suppressed errors, rerun with: -v
==19224== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 8 from 6)
]0;parveza@zuma:~/hw4[parveza@zuma ~/hw4]$ make clean
rm -f *.o *.jpg PhotoLab PhotoLabTest bw.ppm sharpen.ppm hue.ppm noise.ppm posterize.ppm blur.ppm brightnessandcontrast.ppm enlarge.ppm square.ppm original.ppm libFilter.a libFileIO.a
]0;parveza@zuma:~/hw4[parveza@zuma ~/hw4]$ exit
exit

Script done on Sun 01 Mar 2020 07:18:26 PM PST
